import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

function newsPost() {
    return(
        <div className={styles.container}>
        <Head>
           <title>Out of Step UK</title>
           <meta name="description" content="Generated by create next app" />
           <link rel="icon" href="/favicon.ico" />
         </Head>
   
        <div className={styles.header}>
            <h1 className={styles.title}>
                Out of Step UK
            </h1>
            <h3>
                News and blog
            </h3>
        </div>
         
        <div className=''>
          <nav>
          <ul className='flex flex-row justify-evenly bg-black font-bold text-white'>
            <li className='hover:text-gray-400'>
              <a className={styles.navlink} href='../latestissue'>Latest Issue</a>
            </li>
            <li className='hover:text-gray-400'>
              <a className={styles.navlink} href='../news'>News</a>
            </li>
            <li className='hover:text-gray-400'>
              <a className={styles.navlink} href='../reviews'>Reviews</a>
            </li>
            <li className='hover:text-gray-400'>
              <a className={styles.navlink} href='../interviews'>Interviews</a>
            </li>
          </ul>
          </nav>
      </div>

      <main>
        <div className=''>
            <h1>Post Title</h1>

            <h4>Opening paragraph</h4>

            <p>
               Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Netus et malesuada fames ac turpis egestas sed tempus urna.
               Ut faucibus pulvinar elementum integer enim neque volutpat. Vel facilisis volutpat est velit egestas dui id. Sed blandit libero volutpat sed cras. Ornare suspendisse sed nisi lacus sed viverra. Porttitor lacus luctus accumsan tortor posuere ac ut consequat semper. Sagittis id consectetur purus ut faucibus pulvinar elementum integer enim.
               Condimentum lacinia quis vel eros donec ac. Id diam maecenas ultricies mi eget mauris pharetra et ultrices. Mattis vulputate enim nulla aliquet. Arcu felis bibendum ut tristique et egestas quis ipsum. Eget nullam non nisi est sit amet facilisis magna etiam. Viverra vitae congue eu consequat ac felis donec et odio.

               Commodo odio aenean sed adipiscing diam donec adipiscing. Non curabitur gravida arcu ac tortor. At quis risus sed vulputate odio ut enim blandit.
               Consequat nisl vel pretium lectus quam. Egestas congue quisque egestas diam in arcu cursus. Ligula ullamcorper malesuada proin libero nunc consequat interdum varius. Arcu felis bibendum ut tristique et. Convallis a cras semper auctor neque vitae tempus. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit.
               Faucibus a pellentesque sit amet porttitor eget dolor. Proin nibh nisl condimentum id venenatis a condimentum vitae sapien. Blandit volutpat maecenas volutpat blandit. Lectus mauris ultrices eros in. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant morbi.

               Sed sed risus pretium quam vulputate dignissim. Eu augue ut lectus arcu bibendum at. Scelerisque varius morbi enim nunc faucibus a pellentesque sit amet. Sollicitudin nibh sit amet commodo nulla facilisi. Nam libero justo laoreet sit amet cursus sit amet. Sagittis vitae et leo duis ut diam quam nulla.
               Morbi blandit cursus risus at. Diam in arcu cursus euismod quis viverra nibh cras pulvinar. Massa sed elementum tempus egestas sed sed risus pretium quam. Cras pulvinar mattis nunc sed. Mi quis hendrerit dolor magna eget est lorem ipsum. Ultricies mi eget mauris pharetra et. Sed arcu non odio euismod lacinia at quis risus.
               Magna sit amet purus gravida quis blandit turpis cursus in. Luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor. In nisl nisi scelerisque eu ultrices vitae auctor eu. Nunc non blandit massa enim nec. Quam quisque id diam vel quam elementum pulvinar etiam non. Ornare aenean euismod elementum nisi quis eleifend quam.
            </p>

        </div>
      </main>
   
         <footer className={styles.footer}>
           <a
             href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
             target="_blank"
             rel="noopener noreferrer"
           >
             Powered by{' '}
             <span className={styles.logo}>
               <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
             </span>
           </a>
         </footer>
       </div> 
    )
}

export default newsPost