import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'

function newsPost() {
    return(
        <div className={styles.container}>
        <Head>
           <title>Out of Step UK</title>
           <meta name="description" content="Generated by create next app" />
           <link rel="icon" href="/favicon.ico" />
         </Head>
   
        <div className={styles.header}>
            <h1 className={styles.title}>
                Out of Step UK
            </h1>
            <h3>
                News and blog
            </h3>
        </div>
         
        <div className=''>
          <nav>
          <ul className='flex flex-row justify-evenly bg-black font-bold text-white'>
            <li className='hover:text-gray-400'>
              <a className={styles.navlink} href='../latestissue'>Latest Issue</a>
            </li>
            <li className='hover:text-gray-400'>
              <a className={styles.navlink} href='../news'>News</a>
            </li>
            <li className='hover:text-gray-400'>
              <a className={styles.navlink} href='../reviews'>Reviews</a>
            </li>
            <li className='hover:text-gray-400'>
              <a className={styles.navlink} href='../interviews'>Interviews</a>
            </li>
          </ul>
          </nav>
      </div>

      <main>
        <div className='container-l p-9'>
            <h1 className='text-7xl my-6'>Post Title</h1>

            <h4 className='text-3xl my-4'>Opening paragraph</h4>

            <p className='my-4'>
               Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Netus et malesuada fames ac turpis egestas sed tempus urna.
               Ut faucibus pulvinar elementum integer enim neque volutpat. Vel facilisis volutpat est velit egestas dui id. Sed blandit libero volutpat sed cras.
               Ornare suspendisse sed nisi lacus sed viverra. Porttitor lacus luctus accumsan tortor posuere ac ut consequat semper. Sagittis id consectetur purus ut faucibus pulvinar elementum integer enim.
               Condimentum lacinia quis vel eros donec ac. Id diam maecenas ultricies mi eget mauris pharetra et ultrices. Mattis vulputate enim nulla aliquet. Arcu felis bibendum ut tristique et egestas quis ipsum. 
               Eget nullam non nisi est sit amet facilisis magna etiam.
               
               Viverra vitae congue eu consequat ac felis donec et odio.
               
            </p>

            <Link href='/news'><h3 className='text-xl underline'>Back too News?</h3></Link>
        </div>
      </main>
   
         <footer className={styles.footer}>
           <a
             href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
             target="_blank"
             rel="noopener noreferrer"
           >
             Powered by{' '}
             <span className={styles.logo}>
               <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
             </span>
           </a>
         </footer>
       </div> 
    )
}

export default newsPost